#!/usr/bin/env bash

#==========================================================================================#
# Name = HBL-Themes                                                                        #
# Functions = Change themes and wallpapers of herbstluftwm automatically and in real time  #
# Depences = feh                                                                           #
# Optional dependencies = picom-rounded-corners                                            #
# Author = Diego Cesare <diegocesare300491@gmail.com>                                      #
#==========================================================================================#

# menu variables

sep="━━━━━━━━━━━━━━━"
sep1="━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# menu

clear
echo -e "$sep1"
echo -e "$sep \033[1;31mHERBSTLUFTWM THEMES\033[m $sep"
echo -e "$sep1"
echo "( 1 ) Cyan 	( 6 ) Red"
echo "( 2 ) Pink 	( 7 ) Blue"
echo "( 3 ) Purple 	( 8 ) Orange"
echo "( 4 ) Green"
echo "( 5 ) Yellow"
echo "$sep1"
echo -e "Select theme >>> \c"


read opc
case $opc in
	1 ) rm ~/.config/herbstluftwm/autostart && cp ~/.config/herbstluftwm/themes/cyan ~/.config/herbstluftwm/autostart
		feh --bg-scale /home/$USER/Images/Cyan.gilr.jpg
		herbstclient reload
		;;
	2 ) rm ~/.config/herbstluftwm/autostart && cp ~/.config/herbstluftwm/themes/pink ~/.config/herbstluftwm/autostart
		feh --bg-scale /home/$USER/Images/Pink.girl.jpg
		herbstclient reload
		;;
	3 ) rm ~/.config/herbstluftwm/autostart && cp ~/.config/herbstluftwm/themes/purple ~/.config/herbstluftwm/autostart;
		feh --bg-scale /home/$USER/Images/Purple.gilr.jpg
		herbstclient reload
		;;
	4 ) rm ~/.config/herbstluftwm/autostart && cp ~/.config/herbstluftwm/themes/green ~/.config/herbstluftwm/autostart;
		feh --bg-scale /home/$USER/Images/Green.girl.jpg
		herbstclient reload
		;;
	5 ) rm ~/.config/herbstluftwm/autostart && cp ~/.config/herbstluftwm/themes/yellow ~/.config/herbstluftwm/autostart;
		feh --bg-scale /home/$USER/Images/Yellow.girl.jpg
		herbstclient reload
		;;
	6 ) rm ~/.config/herbstluftwm/autostart && cp ~/.config/herbstluftwm/themes/red ~/.config/herbstluftwm/autostart;
		feh --bg-scale /home/$USER/Images/Red.girl.jpg
		herbstclient reload
		;;
	7 ) rm ~/.config/herbstluftwm/autostart && cp ~/.config/herbstluftwm/themes/blue ~/.config/herbstluftwm/autostart;
		feh --bg-scale /home/$USER/Images/Blue.gilr.jpg
		herbstclient reload
		;;
	8 ) rm ~/.config/herbstluftwm/autostart && cp ~/.config/herbstluftwm/themes/orange ~/.config/herbstluftwm/autostart;
		feh --bg-scale /home/$USER/Images/Orange.jpg
		herbstclient reload
		;;
esac